### ISSUE TITLE
Install stopped working?

### ISSUE THREAD

**Issue by jaxankey** [bernardokyotoku/pyniscope#5]
On my fresh Anaconda3 setup (Windows 7), I first tried
```
pip install pyniscope
```
This seemed to go according to plan, installing version 0.4.0. However, when I did an `import niscope`, I wasn't able to access (e.g.) `niscope.Scope()`.

I then followed the "Getting Started" wiki entry, and the command
```
python setup.py install
```
only worked when I changed "readme.rtl" to "readme.md" in setup.py.

I think this is a pretty easy fix (at least modifying setup.py). It'd be awesome if pip worked, too, to simplify the Wiki!

Cheers,
Jack

**Comment by jaxankey** [comment]
Okay I just wiped Anaconda3 and installed Anaconda2. Pip installing seems to work now. The setup.py should still have the aforementioned change, and then I think it's all good. Not sure if that was a python3 issue or not, but I guess we're sticking to 2.

**Comment by jvishnefske** [comment]
Thank you for the heads up. I updated the readme to rst in order to work with pypi. I just pushed the change, so setup.py should be consistent now. I am not able to reproduce the pip error you describe. If you have any details to the cause of the pip install problem I would be interested. I am currently installing with pip on windows 7, and python 3.6.1

**Comment by jaxankey** [comment]
I think I found the pip error, so it's nothing to worry about. A student
had just created a "niscope.py" file that was importing instead of your
library -- this wasn't a problem back when it was "niScope". Sorry for the
confusion!
